#!/usr/bin/env python3
"""Export a STATIC, self-contained v2-cockpit gallery for selected studies.

    python scripts/export_dashboard_static.py --studies chicago_schelling germany_auto_market \
        --out ../homepage/gallery

Bakes every JSON view the v2 dashboard requests (/api/state, per-study detail,
per-version detail, agents list, per-agent detail, files inventory, DuckDB
table overview + first page, paper/literature views) into flat files under
<out>/data/ (URL path -> filename: "/" becomes "__", JSON gets a .json suffix,
figures are copied as-is), copies the whole dashboard/web/v2/ frontend, and
injects a small shim into index.html that:
  - rewrites fetch()/img requests for both "<origin>/api/..." (v2's absolute
    apiUrl) and relative "api/..." onto the baked ./data/ files (query strings
    stripped — the dataset tab statically shows page 1),
  - stubs out EventSource (no SSE on a static host),
  - sets window.__SV_STATIC so the UI hides server-only affordances (CSV
    download, pagination),
  - supports deep links: ?study=<id>.

Endpoints intentionally NOT baked (the UI degrades cleanly): /api/chat/ping
(404 -> chat dock shows the hosted-workbench note), /api/me, /api/notices.
The result needs no server-side code — host on any static host.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import time
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "dashboard" / "server"))
import app  # noqa: E402  (the dashboard server module — reused as a library)

# ids/figure names must be URL-literal (the frontend encodeURIComponent()s them and the
# shim decodes back; anything fancier would need percent-encoded filenames on disk).
SAFE = re.compile(r"^[A-Za-z0-9._\-]+$")

SHIM = """<script>
/* static gallery build — generated by scripts/export_dashboard_static.py (do not edit).
   Maps the v2 dashboard's /api/* calls onto baked ./data/ files; no server, no SSE. */
(function () {
  window.__SV_STATIC = true;
  try {
    var q = new URLSearchParams(location.search).get("study");
    if (q) localStorage.setItem("sv_study", q);
  } catch (e) {}
  var BUILD = "__BUILD__";   // stamped per export — busts viewers' cached data from older exports
  var ROOTAPI = location.origin + "/api/";                      // v2 apiUrl resolves against origin
  var RELAPI = new URL("api/", document.baseURI).toString();    // v1-era relative form (belt&braces)
  var norm = function (u) {          // -> the path after "api/", or null if not an API request
    u = String(u);
    if (u.indexOf(ROOTAPI) === 0) u = u.slice(ROOTAPI.length);
    else if (u.indexOf(RELAPI) === 0) u = u.slice(RELAPI.length);
    else if (u.indexOf("/api/") === 0) u = u.slice(5);
    else return null;
    return u.split("?")[0];                                     // static data has no query dimension
  };
  var map = function (rest, ext) {
    return new URL("data/api__" + rest.split("/").map(decodeURIComponent).join("__")
           + ext + "?b=" + BUILD, document.baseURI).toString();
  };
  var origFetch = window.fetch.bind(window);
  window.fetch = function (u, o) {
    var rest = (typeof u === "string") ? norm(u) : null;
    return rest !== null ? origFetch(map(rest, ".json"), o) : origFetch(u, o);
  };
  window.EventSource = function () {
    return { close: function () {}, addEventListener: function () {} };
  };
  new MutationObserver(function () {
    document.querySelectorAll("img").forEach(function (im) {
      var rest = norm(im.getAttribute("src") || "");
      if (rest !== null) im.src = map(rest, "");
    });
  }).observe(document.documentElement,
             { subtree: true, childList: true, attributes: true, attributeFilter: ["src"] });
})();
</script>"""

# Large tables: no CSV is exported beyond the static-export row cap; the first detail page
# holds the same number of rows as the frontend's PAGE
TABLE_PAGE = 50


def _check_safe(name: str, what: str) -> None:
    if not SAFE.match(name):
        raise SystemExit(f"{what} {name!r} is not URL-literal — static export can't map it")


def _fname(path: str) -> str:
    return path.strip("/").replace("/", "__")


def _dump(out: Path, path: str, obj) -> None:
    (out / "data" / (_fname(path) + ".json")).write_text(
        json.dumps(obj, ensure_ascii=False), encoding="utf-8")


def _export_view(out: Path, base: str, detail: dict, d: Path, agent_cap: int) -> int:
    """Bake one cockpit view (a study's live dir OR a version snapshot dir)."""
    n = 0
    _dump(out, base, detail); n += 1
    ag = app.agents_summary(d)
    _dump(out, base + "/agents", ag); n += 1
    for a in ag.get("agents", [])[:agent_cap]:
        aid = a["agent_id"]
        _check_safe(aid, "agent id")
        _dump(out, f"{base}/agent/{aid}", app.agent_detail(d, aid)); n += 1
    figdir = app.study_paths(d)["figures"]
    for name in detail.get("figures", []):
        _check_safe(name, "figure name")
        if (figdir / name).exists():
            shutil.copyfile(figdir / name, out / "data" / _fname(f"{base}/figure/{name}"))
            n += 1
    # v2 cockpit views
    _dump(out, base + "/files", app.files_view(d)); n += 1
    _dump(out, base + "/data/tables", app.data_tables(d)); n += 1
    for t in app.data_tables(d).get("tables", []):
        _dump(out, f"{base}/data/table/{t['name']}",
              app.data_table_rows(d, t["name"], TABLE_PAGE, 0)); n += 1
    _dump(out, base + "/paper", app.paper_view(d)); n += 1
    _dump(out, base + "/literature", app.literature_view(d)); n += 1
    return n


def export(studies: list[str], out: Path, agent_cap: int) -> None:
    for sid in studies:
        _check_safe(sid, "study id")
        if not app.is_study_dir(app.STUDIES_ROOT / sid):
            raise SystemExit(f"unknown study: {sid} (looked in {app.STUDIES_ROOT})")

    if out.exists():
        shutil.rmtree(out)
    (out / "data").mkdir(parents=True)

    # /api/state, restricted to the exported set (the switcher then only offers them)
    state = app.build_state()
    items = {it["study_id"]: it for it in state["studies"]}
    # mode/local_open: a static host is neither the local server (whose hosted-only UI hiding and
    # open-with-system-app buttons are for a checkout) nor a hosted workbench.
    state.update(studies=[items[s] for s in studies], current_id=studies[0],
                 session_active=False, awaiting=False, latest_query=None,
                 mode="static", local_open=False)
    _dump(out, "/api/state", state)

    n_files = 1
    for sid in studies:
        root = app.STUDIES_ROOT / sid
        n_files += _export_view(out, f"/api/study/{sid}", app.build_detail(root), root, agent_cap)
        versions, _cur = app.versions_view(root)
        for v in versions:
            vd, arch = app.version_dir(root, v["id"])
            if vd is None:
                continue
            detail = app.build_detail(vd, study_root=root, viewing=v["id"], archived=arch)
            n_files += _export_view(out, f"/api/study/{sid}/version/{v['id']}", detail, vd, agent_cap)

    # copy the whole v2 frontend directory + inject the shim
    web = REPO_ROOT / "dashboard" / "web" / "v2"
    for f in web.rglob("*"):
        if f.is_file():
            rel = f.relative_to(web)
            dst = out / rel
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(f, dst)
    html = (web / "index.html").read_text(encoding="utf-8")
    shim = SHIM.replace("__BUILD__", time.strftime("%Y%m%d%H%M%S"))
    (out / "index.html").write_text(html.replace("<head>", "<head>\n" + shim, 1),
                                    encoding="utf-8")
    (out / "README.md").write_text(
        "Generated static v2-cockpit gallery — do not edit by hand.\n\n"
        f"    python scripts/export_dashboard_static.py --studies {' '.join(studies)} "
        f"--out <this dir>\n\n"
        "Deep links: index.html?study=<id> for "
        + ", ".join(studies) + "\n", encoding="utf-8")
    print(f"exported {len(studies)} studies -> {out}  ({n_files} data files)")
    for s in studies:
        print(f"  index.html?study={s}")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--studies", nargs="+", required=True,
                    help="study ids to include (first one = default view)")
    ap.add_argument("--out", type=Path, required=True, help="output directory")
    ap.add_argument("--agent-cap", type=int, default=200,
                    help="max per-agent detail files per view (list stays complete)")
    args = ap.parse_args(argv)
    export(args.studies, args.out, args.agent_cap)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
